name: holoviz-skills-history
port: 6000
image: python:3.11-trixie
auth:
  public: true
tags:
  - team:ai-services
  - owner:tpatrick@anaconda.com

dependencies:
  conda:
    panel: 1.9.3
    panel-material-ui: 0.13.0
    hvplot: 0.12.2
    pandas: 3.0.3

commands:
  - panel serve compare_history.py --port 6000 --address 0.0.0.0 --allow-websocket-origin="*" --args eval_results/
